[build-system]
requires = ['setuptools']

[project]

name = 'nomarket'
version = '0.0.1'
description = 'TWSE and TAIFEX nomarket dates'

authors = [
  {name='John Lin', email='jihghong@gmail.com'}
]

[tool.setuptools]

py-modules = ['nomarket']
